"""Render a Markdown report from records in the common schema.

Aligns output to the analysis structure in method/security-instructions.md:
context -> evidence -> interpretation (ATT&CK mapping) -> next steps.
The engine *signals*; explanations and next steps live in the knowledge base under `method/`.
"""
from __future__ import annotations

# Hayabusa abbreviates the levels; descending severity order.
_LEVEL_ORDER = ["crit", "high", "med", "low", "info"]
_LEVEL_LABEL = {"crit": "critical", "high": "high", "med": "medium",
                "low": "low", "info": "informational"}


def _norm_level(lv: str | None) -> str:
    """Normalize level abbreviations."""
    lv = (lv or "info").lower()
    for k in _LEVEL_ORDER:
        if lv.startswith(k):
            return k
    return "info"


def render(records: list[dict], evtx_name: str, scanned_at: str) -> str:
    """Render EVTX detection records as a Markdown report."""
    hosts = sorted({r.get("host.name") for r in records if r.get("host.name")})

    # counts by level
    counts: dict[str, int] = {k: 0 for k in _LEVEL_ORDER}
    for r in records:
        counts[_norm_level(r.get("rule.level"))] += 1
    summary = " · ".join(f"{_LEVEL_LABEL[k]}: {counts[k]}"
                         for k in _LEVEL_ORDER if counts[k])

    # techniques by tactic (only detections with ATT&CK mapping)
    by_tactic: dict[str, set[str]] = {}
    for r in records:
        techs = r.get("attack.techniques") or []
        if not techs:
            continue
        for tac in (r.get("attack.tactics") or ["(tactic not indicated)"]):
            by_tactic.setdefault(tac, set()).update(techs)
    unmapped = sum(1 for r in records if not r.get("attack.techniques"))

    lines: list[str] = []
    lines.append(f"# EVTX Slice → ATT&CK — {evtx_name}")
    lines.append("")
    lines.append("> Report generated by `analysis/` engine (Phase 1: Hayabusa + Sigma rules). "
                 "Detections should be read as **signals** to validate; for technique explanations "
                 "and next steps, read the knowledge base under `method/` (§14 — method/conventions.md).")
    lines.append("")
    lines.append("## Context")
    lines.append("")
    lines.append(f"- Source: `{evtx_name}` (event.source = `evtx`)")
    lines.append(f"- Observed hosts: {', '.join(hosts) if hosts else 'n/d'} "
                 f"(to be anonymized if real data — §9)")
    lines.append(f"- Total detections: {len(records)}" + (f" — {summary}" if summary else ""))
    lines.append(f"- Scan: {scanned_at}")
    lines.append("")

    lines.append("## ATT&CK Techniques Detected")
    lines.append("")
    if by_tactic:
        for tac in sorted(by_tactic):
            techs = sorted(by_tactic[tac])
            techs_str = ", ".join(f"`{t}`" for t in techs)
            lines.append(f"- **{tac}**: {techs_str}")
    else:
        lines.append("No ATT&CK techniques mapped in this slice's detections.")
    if unmapped:
        lines.append("")
        lines.append(f"Additionally {unmapped} detections without explicit ATT&CK mapping "
                     f"(to be evaluated manually).")
    lines.append("")

    lines.append("## Detection Timeline")
    lines.append("")
    lines.append("| @timestamp (UTC) | level | rule | technique | EID | process |")
    lines.append("|---|---|---|---|---|---|")
    for r in sorted(records, key=lambda x: x.get("@timestamp") or ""):
        proc = r.get("process.name") or r.get("process.command_line") or ""
        if len(proc) > 48:
            proc = proc[:45] + "…"
        lines.append("| {ts} | {lv} | {title} | {tech} | {eid} | {proc} |".format(
            ts=r.get("@timestamp", ""),
            lv=_LEVEL_LABEL[_norm_level(r.get("rule.level"))],
            title=(r.get("rule.title") or "").replace("|", "/"),
            tech=r.get("attack.technique") or "",
            eid=r.get("event.code", ""),
            proc=proc.replace("|", "/"),
        ))
    lines.append("")

    lines.append("## Next Steps")
    lines.append("")
    lines.append("1. Validate high/critical level detections against raw evidence "
                 "(not all Sigma rules are free of false positives).")
    lines.append("2. For each relevant technique, retrieve the ATT&CK explanation "
                 "and countermeasures under `method/framework/`.")
    lines.append("3. If data is real, anonymize hosts/users/IPs before "
                 "sharing the report (§9).")
    lines.append("")
    return "\n".join(lines)
