"""CLI: logon analysis (Event ID 4624/4625) of one or more EVTX → Markdown report.

Designed for LATERAL MOVEMENT hunting after a compromise (e.g. initial access via an
edge device, then lateral movement with stolen credentials). Unlike `run_evtx`
(which goes through the Sigma rules and only sees *flagged* logons), here the dedicated
`hayabusa logon-summary` command is used, which enumerates ALL successful/failed logons:
the authoritative source.

The report highlights **remote logons** (Logon Type 3 Network / 8 NetworkCleartext /
9 NewCredentials / 10 RemoteInteractive-RDP) and rare source→destination pairs, which are
the typical lateral-movement pattern. The engine *signals*; validation stays with the analyst.

Usage:
    uv run python -m engine.run_logons <file.evtx> [--out report.md]

Example (public EVTX-ATTACK-SAMPLES sample):
    uv run python -m engine.run_logons ".tools/EVTX-ATTACK-SAMPLES/Lateral Movement/LM_WMI_4624_4688_TargetHost.evtx"
"""
from __future__ import annotations

import argparse
import csv
import datetime as _dt
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from engine import hayabusa_runner  # noqa: E402

# "Remote" logon types: who arrives from the network, not from the local keyboard. They are the
# lateral-movement vectors — network share/WMI/DCOM (3), cleartext auth (8), runas /netonly with
# alternate credentials (9), RDP (10). Type 2 (Interactive) and 5 (Service) stay out.
REMOTE_LOGON_TYPES = {3, 8, 9, 10}


def _parse_type(raw: str) -> tuple[int | None, str]:
    """'3 - Network' → (3, '3 - Network'); non-numeric value → (None, raw)."""
    raw = (raw or "").strip()
    head = raw.split("-", 1)[0].strip()
    try:
        return int(head), raw
    except ValueError:
        return None, raw


def _read_csv(path: Path) -> list[dict]:
    """Read a logon-summary CSV into a list of normalized rows.

    The first column is the count (header 'Successful' or 'Failed'); the others are
    Event, Target Account/Domain/Computer, Logon Type, Source Account/Domain/Computer, Source IP.
    """
    if not path.exists():
        return []
    rows: list[dict] = []
    with path.open(newline="", encoding="utf-8") as fh:
        reader = csv.reader(fh)
        header = next(reader, None)
        if not header:
            return []
        for r in reader:
            if not r or len(r) < 10:
                continue
            try:
                count = int(r[0])
            except ValueError:
                count = 0
            tnum, traw = _parse_type(r[5])
            rows.append({
                "count": count,
                "event": r[1].strip(),
                "target_account": r[2].strip(),
                "target_domain": r[3].strip(),
                "target_computer": r[4].strip(),
                "type_num": tnum,
                "type_label": traw,
                "source_account": r[6].strip(),
                "source_domain": r[7].strip(),
                "source_computer": r[8].strip(),
                "source_ip": r[9].strip(),
            })
    return rows


def _fmt(v: str) -> str:
    """Table cell: empty field or '-' → '—'; pipe neutralized."""
    v = (v or "").strip()
    return "—" if v in ("", "-") else v.replace("|", "/")


def render(successful: list[dict], failed: list[dict],
           evtx_names: list[str], scanned_at: str) -> str:
    hosts = sorted({r["target_computer"] for r in successful + failed if r["target_computer"]})
    remote = sorted((r for r in successful if r["type_num"] in REMOTE_LOGON_TYPES),
                    key=lambda r: (r["count"], r["type_num"] or 0))
    tot_succ = sum(r["count"] for r in successful)
    tot_fail = sum(r["count"] for r in failed)

    lines: list[str] = []
    lines.append(f"# Logon analysis (4624/4625) — {', '.join(evtx_names)}")
    lines.append("")
    lines.append("> Report generated by the `analysis/` engine (`hayabusa logon-summary`). Logons are "
                 "**signals** to validate against the raw evidence; for the interpretation of the "
                 "techniques (T1021 Remote Services, T1078 Valid Accounts) query the RAG (§14).")
    lines.append("")

    lines.append("## Context")
    lines.append("")
    lines.append(f"- Sources: {', '.join(f'`{n}`' for n in evtx_names)}")
    lines.append(f"- Observed destination hosts: {', '.join(hosts) if hosts else 'n/a'} "
                 "(pseudonymize if real data — §9)")
    lines.append(f"- Successful logons (4624): {tot_succ} · failed logons (4625): {tot_fail}")
    lines.append(f"- Scan: {scanned_at}")
    lines.append("")

    lines.append("## Remote logons (potential lateral movement)")
    lines.append("")
    lines.append("Logon Type 3 (Network) / 8 (NetworkCleartext) / 9 (NewCredentials) / "
                 "10 (RemoteInteractive-RDP): accesses coming from the network. Sorted by "
                 "rarity (one-off logons toward a host are the most suspicious in a lateral movement).")
    lines.append("")
    if remote:
        lines.append("| count | type | target account | target host | source account | source host | source IP |")
        lines.append("|---|---|---|---|---|---|---|")
        for r in remote:
            lines.append("| {c} | {t} | {ta} | {tc} | {sa} | {sc} | {ip} |".format(
                c=r["count"], t=_fmt(r["type_label"]),
                ta=_fmt(r["target_account"]), tc=_fmt(r["target_computer"]),
                sa=_fmt(r["source_account"]), sc=_fmt(r["source_computer"]),
                ip=_fmt(r["source_ip"]),
            ))
    else:
        lines.append("No remote logon (type 3/8/9/10) in the analyzed data.")
    lines.append("")

    if failed:
        lines.append("## Failed logons (4625)")
        lines.append("")
        lines.append("High counts or toward multiple accounts = possible brute force / password spraying.")
        lines.append("")
        lines.append("| count | type | target account | target host | source account | source IP |")
        lines.append("|---|---|---|---|---|---|")
        for r in sorted(failed, key=lambda r: -r["count"]):
            lines.append("| {c} | {t} | {ta} | {tc} | {sa} | {ip} |".format(
                c=r["count"], t=_fmt(r["type_label"]),
                ta=_fmt(r["target_account"]), tc=_fmt(r["target_computer"]),
                sa=_fmt(r["source_account"]), ip=_fmt(r["source_ip"]),
            ))
        lines.append("")

    lines.append("## Next steps")
    lines.append("")
    lines.append("1. For each rare remote logon, correlate source host/IP with the inventory: "
                 "is it an expected administrative access or a lateral hop?")
    lines.append("2. Cross-reference the accounts used remotely with the time window of the "
                 "initial compromise (e.g. edge device / SonicWall SMA) — stolen credentials.")
    lines.append("3. Retrieve the countermeasures for T1021 / T1078 from the RAG (collection `knowledge_cyber`).")
    lines.append("4. If the data is real, pseudonymize hosts/accounts/IPs before sharing (§9).")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Logon analysis 4624/4625 → report (lateral movement).")
    ap.add_argument("evtx", nargs="+", help="one or more .evtx files to analyze")
    ap.add_argument("--out", help="path of the Markdown report (default: reports/logon-<date>.md)")
    args = ap.parse_args(argv)

    paths = [Path(p) for p in args.evtx]
    for p in paths:
        if not p.exists():
            print(f"error: EVTX does not exist: {p}", file=sys.stderr)
            return 2

    # A missing Hayabusa is an INSTALLATION problem with a printed remedy, not a stack trace.
    # `run_mft` and `run_pcap` already exit with one line here; these two raised through main and
    # buried the sentence that says what to download under a traceback.
    try:
        hayabusa_runner.find_binary()
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    scanned_at = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    successful: list[dict] = []
    failed: list[dict] = []

    with tempfile.TemporaryDirectory() as td:
        for i, evtx in enumerate(paths):
            print(f"[{i + 1}/{len(paths)}] logon-summary on {evtx.name}…")
            prefix = Path(td) / f"logon-{i}"
            # The CSVs live in the tempdir and are removed when the context manager exits:
            # the Hayabusa output with client accounts/IPs does not stay on disk (§9/§10).
            succ_csv, fail_csv = hayabusa_runner.run_logon_summary(evtx, prefix)
            successful.extend(_read_csv(succ_csv))
            failed.extend(_read_csv(fail_csv))

    md = render(successful, failed, [p.name for p in paths], scanned_at)
    out = Path(args.out) if args.out else (
        Path(__file__).resolve().parents[1] / "reports"
        / f"logon-{_dt.date.today().isoformat()}.md"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    print(f"\nReport: {out}")

    remote = sum(1 for r in successful if r["type_num"] in REMOTE_LOGON_TYPES)
    print(f"Remote logons (type 3/8/9/10): {remote} rows · failed: {len(failed)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
