"""CLI: analyze a PCAP → network report (flows, DNS, ATT&CK signals).

Orchestration: tshark (adapter) → common schema → network analytics →
Markdown report. Everything local and offline (DESIGN §2). Complements EVTX slice:
same common schema, network domain.

Usage:
    uv run python -m engine.run_pcap <file.pcap> [--out report.md]
"""
from __future__ import annotations

import argparse
import datetime as _dt
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from adapters import pcap_tshark  # noqa: E402
from analytics.recipes import COMMON_PORTS as _STANDARD_PORTS  # noqa: E402

# "Expected" ports: a destination outside _STANDARD_PORTS is a signal (not proof).
# Single SOT in analytics.recipes.COMMON_PORTS (§16): reuse its value here, no
# divergent copy (previously the two sets differed, e.g., on 8443/139/5985).


def _analyze(records: list[dict]) -> dict:
    conversations: dict[tuple, dict] = {}
    talkers_src: Counter = Counter()
    bytes_src: Counter = Counter()
    dns: Counter = Counter()
    nonstd: dict[tuple, int] = defaultdict(int)

    for r in records:
        src, dst = r.get("source.ip"), r.get("destination.ip")
        port = r.get("destination.port")
        transport = r.get("network.transport") or ""
        nbytes = r.get("network.bytes") or 0
        if src:
            talkers_src[src] += 1
            bytes_src[src] += nbytes
        if r.get("dns.question.name"):
            dns[r["dns.question.name"]] += 1
        if src and dst:
            key = (src, dst, port, transport)
            c = conversations.setdefault(key, {"packets": 0, "bytes": 0})
            c["packets"] += 1
            c["bytes"] += nbytes
            if port and port not in _STANDARD_PORTS:
                nonstd[(dst, port, transport)] += 1

    return {
        "records": records,
        "conversations": conversations,
        "talkers_src": talkers_src,
        "bytes_src": bytes_src,
        "dns": dns,
        "nonstd": nonstd,
    }


def _merge_records(
    tshark_records: list[dict], zeek_records: list[dict]
) -> list[dict]:
    """Merge and deduplicate tshark and Zeek records per flow.

    The dedup key is ``(source.ip, destination.ip, destination.port,
    network.transport)``. Zeek fields override tshark where both exist
    (Zeek is richer at the application level). Zeek records not paired
    with a tshark record are preserved.
    """
    zeek_by_key: dict[tuple, dict] = {}
    for zr in zeek_records:
        key = (
            zr.get("source.ip"),
            zr.get("destination.ip"),
            zr.get("destination.port"),
            zr.get("network.transport"),
        )
        zeek_by_key[key] = zr

    merged: list[dict] = []
    used: set[tuple] = set()

    for tr in tshark_records:
        key = (
            tr.get("source.ip"),
            tr.get("destination.ip"),
            tr.get("destination.port"),
            tr.get("network.transport"),
        )
        if key in zeek_by_key:
            merged.append({**tr, **zeek_by_key[key]})
            used.add(key)
        else:
            merged.append(tr)

    # Zeek records without tshark counterpart
    for key, zr in zeek_by_key.items():
        if key not in used:
            merged.append(zr)

    return merged


def _hints(a: dict) -> list[str]:
    """ATT&CK signals as HYPOTHESES to validate (never assertions — §6)."""
    out = []
    if a["dns"]:
        out.append("DNS queries present: if toward rare/algorithmic domains or with "
                   "anomalous volume, consider **C2/exfiltration over DNS** (`T1071.004`).")
    if a["nonstd"]:
        dests = ", ".join(f"{d}:{p}/{t}" for (d, p, t) in sorted(a["nonstd"]))
        out.append(f"Connections to non-standard ports ({dests}): consider "
                   f"**Non-Standard Port** (`T1571`) / C2 over atypical channel.")
    # exfil: destination with large outbound bytes (indicative threshold)
    big = [(k, v["bytes"]) for k, v in a["conversations"].items() if v["bytes"] > 1_000_000]
    if big:
        out.append("High outbound volumes to a destination: consider "
                   "**Exfiltration** (`T1041`/`TA0010`).")
    if not out:
        out.append("No obvious heuristic signals in this slice. Absence of signal "
                   "is not proof of absence of activity (e.g., encrypted traffic).")
    return out


def render(a: dict, pcap_name: str, scanned_at: str) -> str:
    """Render PCAP analysis as Markdown report."""
    records = a["records"]
    L: list[str] = []
    L.append(f"# PCAP Analysis — {pcap_name}")
    L.append("")
    L.append("> Report generated by `analysis/` engine (PCAP adapter via tshark + Zeek). "
             "**ATT&CK signals** below are *hypotheses* to validate against evidence, "
             "not conclusions; for explanations read the knowledge base under `method/` (§14 — method/conventions.md).")
    L.append("")
    L.append("## Context")
    L.append("")
    L.append(f"- Source: `{pcap_name}` (event.source = `pcap`)")
    if a.get("n_zeek"):
        L.append(f"- IP packets analyzed: {len(records)} "
                 f"({a['n_tshark']} from tshark, {a['n_zeek']} from Zeek)")
    else:
        L.append(f"- IP packets analyzed: {len(records)}")
    L.append(f"- Distinct source hosts: {len(a['talkers_src'])} "
             f"(anonymize internal IPs if real data — §9)")
    L.append(f"- Scan: {scanned_at}")
    L.append("")

    L.append("## Conversations / Flows")
    L.append("")
    L.append("| source.ip | destination.ip | port | transport | packets | bytes |")
    L.append("|---|---|---|---|---|---|")
    for (src, dst, port, transport), v in sorted(
            a["conversations"].items(), key=lambda kv: -kv[1]["packets"]):
        L.append(f"| {src} | {dst} | {port or ''} | {transport} | "
                 f"{v['packets']} | {v['bytes']} |")
    L.append("")

    L.append("## Top Talker (by source IP)")
    L.append("")
    for ip, pkts in a["talkers_src"].most_common(10):
        L.append(f"- {ip}: {pkts} packets, {a['bytes_src'][ip]} bytes")
    L.append("")

    if a["dns"]:
        L.append("## DNS Queries")
        L.append("")
        for name, n in a["dns"].most_common():
            L.append(f"- `{name}`" + (f" ×{n}" if n > 1 else ""))
        L.append("")

    L.append("## ATT&CK Signals (hypotheses)")
    L.append("")
    for h in _hints(a):
        L.append(f"- {h}")
    L.append("")

    L.append("## Next Steps")
    L.append("")
    L.append("1. Validate signals against raw evidence (e.g., inspect suspicious conversation "
             "payloads, resolve domains, contextualize ports).")
    L.append("2. Correlate with endpoints (EVTX/EDR) on the same hosts/time window.")
    L.append("3. Read the cited techniques under `method/framework/` (ATT&CK notes).")
    L.append("4. Anonymize internal IPs before sharing the report (§9).")
    L.append("")
    return "\n".join(L)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="PCAP Analysis → network report.")
    ap.add_argument("pcap", help="path to .pcap/.pcapng file")
    ap.add_argument("--out", help="path to report (default: reports/<name>-<date>.md)")
    args = ap.parse_args(argv)

    pcap = Path(args.pcap)
    if not pcap.exists():
        print(f"error: PCAP not found: {pcap}", file=sys.stderr)
        return 2

    scanned_at = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    print(f"[1/3] tshark on {pcap.name}…")
    tshark_records = pcap_tshark.load_records(pcap)
    print(f"[2/3] Zeek on {pcap.name}…")
    try:
        from adapters import pcap_zeek
        zeek_records = pcap_zeek.load_records(pcap)
    except FileNotFoundError:
        zeek_records = []
        print("  (Zeek not installed, skipped)")
    except Exception as exc:
        zeek_records = []
        print(f"  (Zeek error: {exc})")
    print(f"[3/3] Merge + analytics ({len(tshark_records)} tshark + {len(zeek_records)} Zeek)…")
    records = _merge_records(tshark_records, zeek_records)
    a = _analyze(records)
    a["n_tshark"] = len(tshark_records)
    a["n_zeek"] = len(zeek_records)
    md = render(a, pcap_name=pcap.name, scanned_at=scanned_at)

    out = Path(args.out) if args.out else (
        Path(__file__).resolve().parents[1] / "reports"
        / f"{pcap.stem}-{_dt.date.today().isoformat()}.md"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    print(f"\nReport: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
